from django.db import models

# Create your models here.
class UserDetail(models.Model):
    name = models.TextField()
    email = models.EmailField()
    password =models.CharField(max_length=50)
    age = models.IntegerField()
    gender = models.TextField()
    institute = models.TextField()
    designation = models.TextField()

    def __str__(self):
        return self.name
    
# Model for Welbeing
class WellBeing(models.Model):
    q1 = models.CharField(max_length=100)
    q2 = models.CharField(max_length=100)
    q3 = models.CharField(max_length=100)
    q4 = models.CharField(max_length=100)
    q5 = models.CharField(max_length=100)
    q6 = models.CharField(max_length=100)
    q7 = models.CharField(max_length=100)
    q8 = models.CharField(max_length=100)
    q9 = models.CharField(max_length=100)
    q10 = models.CharField(max_length=100)
    q11 = models.CharField(max_length=100)
    q12 = models.CharField(max_length=100)
    q13 = models.CharField(max_length=100)
    q14 = models.CharField(max_length=100)
    q15 = models.CharField(max_length=100)
    q16 = models.CharField(max_length=100)
    q17 = models.CharField(max_length=100)
    q18 = models.CharField(max_length=100)

# Model for Psychologyadjustment
class Psychologyadjustment(models.Model):
    q1 = models.IntegerField()
    q2 = models.IntegerField()
    q3 = models.IntegerField()
    q4 = models.IntegerField()
    q5 = models.IntegerField()
    q6 = models.IntegerField()
    q7 = models.IntegerField()
    q8 = models.IntegerField()
    q9 = models.IntegerField()
    result = models.IntegerField()

# Model for Stress
class Stress(models.Model):
    q1 = models.IntegerField()
    q2 = models.IntegerField()
    q3 = models.IntegerField()
    q4 = models.IntegerField()
    q5 = models.IntegerField()
    q6 = models.IntegerField()
    q7 = models.IntegerField()
    q8 = models.IntegerField()
    q9 = models.IntegerField()
    q10 = models.IntegerField()

# Model for Anxiety
class Anxiety(models.Model):
    q1 = models.IntegerField()
    q2 = models.IntegerField()
    q3 = models.IntegerField()
    q4 = models.IntegerField()
    q5 = models.IntegerField()
    q6 = models.IntegerField()
    q7 = models.IntegerField()
    q8 = models.IntegerField()
    q9 = models.IntegerField()
    q10 = models.IntegerField()
    q11 = models.IntegerField()
    q12 = models.IntegerField()
    q13 = models.IntegerField()
    q14 = models.IntegerField()
    q15 = models.IntegerField()
    q16 = models.IntegerField()
    q17 = models.IntegerField()
    q18 = models.IntegerField()
    q19 = models.IntegerField()
    q20 = models.IntegerField()
    q21 = models.IntegerField()
    q22 = models.IntegerField()
    q23 = models.IntegerField()
    q24 = models.IntegerField()
    q25 = models.IntegerField()
    q26 = models.IntegerField()
    q27 = models.IntegerField()
    q28 = models.IntegerField()
    q29 = models.IntegerField()
    q30 = models.IntegerField()
    q31 = models.IntegerField()
    q32 = models.IntegerField()
    q33 = models.IntegerField()
    q34 = models.IntegerField()
    q35 = models.IntegerField()
    q36 = models.IntegerField()
    q37 = models.IntegerField()
    q38 = models.IntegerField()
    q39 = models.IntegerField()
    q40 = models.IntegerField()