# Generated by Django 4.0.3 on 2022-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('institute', models.TextField()),
                ('designation', models.TextField()),
            ],
        ),
    ]
