# Generated by Django 4.0.3 on 2022-05-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employee_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='UserDetails',
        ),
    ]
