# Generated by Django 4.0.3 on 2022-05-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellBeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=100)),
                ('q2', models.CharField(max_length=100)),
                ('q3', models.CharField(max_length=100)),
                ('q4', models.CharField(max_length=100)),
                ('q5', models.CharField(max_length=100)),
                ('q6', models.CharField(max_length=100)),
                ('q7', models.CharField(max_length=100)),
                ('q8', models.CharField(max_length=100)),
                ('q9', models.CharField(max_length=100)),
                ('q10', models.CharField(max_length=100)),
                ('q11', models.CharField(max_length=100)),
                ('q12', models.CharField(max_length=100)),
                ('q13', models.CharField(max_length=100)),
                ('q14', models.CharField(max_length=100)),
                ('q15', models.CharField(max_length=100)),
                ('q16', models.CharField(max_length=100)),
                ('q17', models.CharField(max_length=100)),
                ('q18', models.CharField(max_length=100)),
            ],
        ),
    ]
