# Generated by Django 4.0.3 on 2022-05-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_q10_stress_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stress',
            new_name='Psychologyadjustment',
        ),
    ]
