# Generated by Django 4.0.3 on 2022-05-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_stress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anxiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('q9', models.IntegerField()),
                ('q10', models.IntegerField()),
                ('q11', models.IntegerField()),
                ('q12', models.IntegerField()),
                ('q13', models.IntegerField()),
                ('q14', models.IntegerField()),
                ('q15', models.IntegerField()),
                ('q16', models.IntegerField()),
                ('q17', models.IntegerField()),
                ('q18', models.IntegerField()),
                ('q19', models.IntegerField()),
                ('q20', models.IntegerField()),
                ('q21', models.IntegerField()),
                ('q22', models.IntegerField()),
                ('q23', models.IntegerField()),
                ('q24', models.IntegerField()),
                ('q25', models.IntegerField()),
                ('q26', models.IntegerField()),
                ('q27', models.IntegerField()),
                ('q28', models.IntegerField()),
                ('q29', models.IntegerField()),
                ('q30', models.IntegerField()),
                ('q31', models.IntegerField()),
                ('q32', models.IntegerField()),
                ('q33', models.IntegerField()),
                ('q34', models.IntegerField()),
                ('q35', models.IntegerField()),
                ('q36', models.IntegerField()),
                ('q37', models.IntegerField()),
                ('q38', models.IntegerField()),
                ('q39', models.IntegerField()),
                ('q40', models.IntegerField()),
            ],
        ),
    ]
